export PYTHONPATH := $(CURDIR)/../../uvm/:$(CURDIR)/../../uvm/wrapper:$(PYTHONPATH)

SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES +=  $(CURDIR)/../../rtl/*.v \
                    $(CURDIR)/../../uvm/wrapper/uart_rtl_wrapper.v

TOPLEVEL = uart_rtl_wrapper
COCOTB_TEST_MODULES = components.test_uart

# Specify log file for simulation output
SIM_LOG_FILE = $(CURDIR)/testbench.log

# Enable VCD waveform dump
# export WAVES = 1

# Include Cocotb simulation rules
include $(shell cocotb-config --makefiles)/Makefile.sim